apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
  namespace: app-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: quarkus/quarkus-opentrace-svc1
        imagePullPolicy: Never
        name: quarkus-svc1
        ports:
          - containerPort: 8080