apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1-svc
  name: app1-svc
  namespace: app-space
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app1